# Generated by Django 3.2.10 on 2021-12-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20211226_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='domiciliio',
            new_name='domicilio',
        ),
    ]
