# Generated by Django 3.2.10 on 2021-12-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_rename_domiciliio_persona_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='no_calle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
